# source https://github.com/actions/labeler/blob/master/README.md
# Add 'repo' label to any root file changes
NSFW Adult Material:
  - submit_here/adult.mypdns.cloud/hosts.list
  - submit_here/adult.mypdns.cloud/domains.list
  - submit_here/adult.mypdns.cloud/mobile.list
  - submit_here/adult.mypdns.cloud/rpz-ip
  - submit_here/adult.mypdns.cloud/wildcard.list
  - submit_here/adult.mypdns.cloud/wildcard.rpz-nsdname

Snuff:
  - submit_here/snuff.txt

Whitelist:
  - submit_here/whitelist.txt

# Add '@domain/core' label to any change within the 'core' package
#@domain/core:
#  - package/core/*
#  - package/core/**/*

# Add 'test' label to any change to *.spec.js files within the source dir
#test:
#  - src/**/*.spec.js
