os: linux
dist: focal

language: generic

cache:
  #pip: true
  directories:
    - '$HOME/db/'

env:
  global:
    - GIT_NAME: 'spirillen'
    - GIT_EMAIL: '44526987+spirillen@users.noreply.github.com'
    - TRAVIS_REPO_SLUG: '${TRAVIS_REPO_SLUG}'
    - GIT_BRANCH: $"{TRAVIS_BRANCH}"
    - TZ: UTC
    # Variables info: https://pyfunceble.readthedocs.io/en/dev/components/environment-variables.html#what-do-we-use-and-why
    - PYFUNCEBLE_CONFIG_DIR: '${TRAVIS_BUILD_DIR}/.pyfunceble/'
    - PYFUNCEBLE_OUTPUT_LOCATION: '${TRAVIS_BUILD_DIR}/active_domains/'
    - PYFUNCEBLE_AUTO_CONFIGURATION: yes
    - PYFUNCEBLE_DB_CHARSET="${DB_CHARSET}"
    - PYFUNCEBLE_DB_HOST="${DB_HOST}"
    - PYFUNCEBLE_DB_NAME="${DB_NAME}"
    - PYFUNCEBLE_DB_USERNAME="${DB_USERNAME}"
    - PYFUNCEBLE_DB_PASSWORD="${DB_PASSWORD}"
    - PYFUNCEBLE_DB_PORT="${DB_PORT}"
    #- PYFUNCEBLE_DEBUG: true
    #- PYFUNCEBLE_DEBUG_ON_SCREEN: true
    - PYTHON_VERSION: 3.9.0

addons:
  #mariadb: '10.5'
  apt:
    packages:
      - dos2unix
      - msttcorefonts
      - lsof
      - gosu

install:
  #- sudo bash "${TRAVIS_BUILD_DIR}/travissetup_recursor.sh"
  - wget -q 'https://raw.githubusercontent.com/dns-test/script-hub/master/recursor/setup_recursor.sh' -O "$HOME/setup_recursor.sh" && sudo bash "$HOME/setup_recursor.sh"
  - export PATH="${HOME}/miniconda/bin:${PATH}"
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda create -q -n test-environment python="${PYTHON_VERSION}"
  - source activate test-environment
  - python --version --version
  - pip --version
  - conda --version
  #- pip -q install --no-cache-dir -U PyFunceble-dev
  #- pip -q install --no-cache-dir -U ultimate-hosts-blacklist-whitelist-dev
  - pip -q install --no-cache-dir -U git+https://github.com/funilrys/PyFunceble@dev ultimate-hosts-blacklist-whitelist-dev dnspython[dnssec,idna]
  - pyfunceble --version

git:
  depth: 2

# paste config here
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash "${TRAVIS_BUILD_DIR}/scripts/PrepareData.sh" && bash "${TRAVIS_BUILD_DIR}/scripts/DataTesting.sh"; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash "${TRAVIS_BUILD_DIR}/scripts/run_on_pull_requests"; fi'
