name: PyFunceble CI tests
on:
  push:
    branches:
      - 'master'
      - 'data-testing'
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron: '0 */4 * * *'

env:
  PYFUNCEBLE_AUTO_CONFIGURATION: 'YES'
  GIT_NAME: '${{ secrets.GIT_NAME }}'
  GIT_EMAIL: '${{ secrets.GIT_EMAIL }}'
  PYFUNCEBLE_DEBUG: True
  # PYFUNCEBLE_DEBUG_LVL: debug
  PYFUNCEBLE_DEBUG_ON_SCREEN: true
  PYFUNCEBLE_CONFIG_DIR: '${{ github.workspace }}/.pyfunceble'
  PYFUNCEBLE_OUTPUT_LOCATION: '${{ github.workspace }}/active_domains/'
  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  BUILD_NUMBER: '${{ github.run_number }}'

jobs:
  test_and_push:
    name: Run PyFunceble against the files and push result to repository
    runs-on: '${{ matrix.os }}'

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - '3.9.1'
        os:
          - ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        name: Clone repository
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      # - name: Install conda AS WSL sucks
      #   run: |
      #     bash "${{ github.workspace }}/scripts/conda_install.sh"

      - name: setup-conda
        uses: s-weigand/setup-conda@v1.0.5
        with:
          python-version: 3.9.1
          activate-conda: true
          update-conda: true

      - name: Conda environment creation
        run: |
          conda create -q -n pyfunceble4
          source activate pyfunceble4

      - name: Python version
        run: python --version

      - name: Conda version
        run: conda --version

      - name: Install PyFunceble
        run: |
          pip install --no-cache-dir --pre PyFunceble-dev

      - name: Get PyFunceble version
        run: |
          PyFunceble --version

      - name: Install UHBW
        run: |
          pip install --no-cache-dir ultimate-hosts-blacklist-whitelist-dev

      - name: Get UHBW version
        run: |
          uhb_whitelist --version

      # - name: Run Whitelist
      #   run: |
      #     bash "${{ github.workspace }}/scripts/PrepareData.sh"

      - name: Run Data testing
        run: |
          echo "$(date +'%s')" > "${{ github.workspace }}/.trigger"
          # bash "${{ github.workspace }}/scripts/DataTesting.sh"
          pyfunceble --ci --preload --dots  -ex --hierarchical \
            --logging-level critical \
            --autosave-minutes 25 -f "${{ github.workspace }}/submit_here/adult.mypdns.cloud/domains.list" \
            "${{ github.workspace }}/submit_here/adult.mypdns.cloud/hosts.list" \
            "${{ github.workspace }}/submit_here/adult.mypdns.cloud/mobile.list" \
            "${{ github.workspace }}/submit_here/adult.mypdns.cloud/rpz-ip" \
            "${{ github.workspace }}/submit_here/adult.mypdns.cloud/snuff.list" \
            "${{ github.workspace }}/submit_here/adult.mypdns.cloud/white.list" \
            "${{ github.workspace }}/submit_here/adult.mypdns.cloud/wildcard.list" \
            "${{ github.workspace }}/submit_here/adult.mypdns.cloud/wildcard.rpz-nsdname" \
            "${{ github.workspace }}/submit_here/strict.adult.mypdns.cloud/domains.list" \
            "${{ github.workspace }}/submit_here/strict.adult.mypdns.cloud/hosts.list" \
            "${{ github.workspace }}/submit_here/strict.adult.mypdns.cloud/rpz-ip" \
            "${{ github.workspace }}/submit_here/strict.adult.mypdns.cloud/wildcard.list" \
            "${{ github.workspace }}/submit_here/strict.adult.mypdns.cloud/wildcard.rpz-nsdname" \
            --ci-command "echo $(date +'%s') > ${{ github.workspace }}/.trigger"
